gcc: Make it buildable by gcc6
Fix the build error:
| .../include/linux/compiler-gcc.h:106:30: fatal error: linux/compiler-gcc6.h: No such file or directory
| #include gcc_header(__GNUC__)

Caused by the GCC-6 compiler specific header absence

Signed-off-by: Zhenhua Luo <zhenhua.luo@nxp.com>